### ISSUE TITLE
2 exceptions: no module train_log and file not found

### ISSUE THREAD

**Issue by KiaWeb** [hzwer/arXiv2021-RIFE#251]
Log when running RIFE:
```
Traceback (most recent call last):
  File "C:\Users\lyly2\Desktop\arXiv2021-RIFE\inference_video.py", line 92, in <module>
    model.load_model(args.modelDir, -1)
  File "C:\Users\lyly2\Desktop\arXiv2021-RIFE\model\oldmodel\RIFE_HDv2.py", line 164, in load_model
    convert(torch.load('{}/flownet.pkl'.format(path), map_location=device)))
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'train_log/flownet.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lyly2\Desktop\arXiv2021-RIFE\inference_video.py", line 95, in <module>
    from train_log.RIFE_HDv3 import Model
ModuleNotFoundError: No module named 'train_log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lyly2\Desktop\arXiv2021-RIFE\inference_video.py", line 102, in <module>
    model.load_model(args.modelDir, -1)
  File "C:\Users\lyly2\Desktop\arXiv2021-RIFE\model\oldmodel\RIFE_HD.py", line 179, in load_model
    convert(torch.load('{}/flownet.pkl'.format(path), map_location=device)))
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\lyly2\AppData\Roaming\Python\Python310\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'train_log/flownet.pkl'
```

**Comment by KiaWeb** [comment]
`torchrun` does not exist, and when I try running torch with `py -m (torch) train.py`, it doesn't really give the log.

**Comment by KiaWeb** [comment]
figured it out
